#!/usr/bin/env python3
"""
Zotero AI-Powered Paper Organizer - Dual-Track Classification System
=====================================================================

Automatically classifies papers into TWO simultaneous structures:
1. Track A (📚 Archive): Subject-based hierarchy for easy retrieval
2. Track B (💡 Idea Lab): Question-based hierarchy for scientific exploration

Key Features:
- Dual-track classification (one paper → two collections)
- Profile-driven AI prompts (loads user_profile.json from profiler.py)
- Local caching to minimize API calls
- Batch processing for efficiency
- Smart tagging to prevent duplicate processing
- Targeted collection processing support

Author: Prof. Chengming Li (SCUT)
"""

import time
import json
import math
import os
import sys
from pyzotero import zotero
from google import genai

# 配置加载
from config_loader import get_config_from_args_or_interactive

config = get_config_from_args_or_interactive()
if config is None:
    print("[ERROR] 无法加载配置文件，程序退出")
    sys.exit(1)

# ================= 1. Configuration =================

# Target collection to process (None = process entire library)
TARGET_COLLECTION_PATH = getattr(config, 'TARGET_COLLECTION_PATH', None)

# Processing settings
DRY_RUN = False                      # True = test mode, False = actually move items
BATCH_SIZE = 5                      # Number of papers to classify per API call
AUTO_TAG_NAME = "auto_organized"    # Tag to prevent duplicate processing
PROFILE_FILE = 'user_profile.json'  # User profile generated by profiler.py
CACHE_FILE = "collections_cache.json"  # Local cache for collection IDs

# ================= 2. Dual-Track Taxonomy Definition =================

# Comprehensive Dual-Track Taxonomy for Hydrology Research
PREFERRED_TAXONOMY = {
    "Track_A_Archive": {
        "description": "Standard disciplinary classification for systematic retrieval",
        "emoji": "📚",
        "structure": {
            "Processes": [
                "Evapotranspiration (ET)",
                "Runoff & Streamflow",
                "Soil Moisture",
                "Groundwater",
                "Cryosphere (Snow & Glacier)"
            ],
            "Hazards": [
                "Drought/Flash Drought",
                "Flood",
                "Compound Events/DFA",
                "Heatwaves & Extremes"
            ],
            "Methodology": [
                "Remote Sensing/Retrieval",
                "Deep Learning (LSTM_CNN)",
                "Data Fusion",
                "Triple Collocation/Uncertainty",
                "Statistical Methods"
            ],
            "Applications": [
                "Water Resources Management",
                "Climate Change Impact",
                "Agricultural Systems",
                "Early Warning Systems"
            ]
        }
    },
    "Track_B_Idea_Lab": {
        "description": "Taste-driven classification based on scientific questions and mechanisms",
        "emoji": "💡",
        "structure": {
            "Mechanism": [
                "Abrupt Transitions/Phase Change",
                "Land-Atmosphere Coupling",
                "Feedback Loops & Cascades",
                "Threshold Behavior"
            ],
            "Data Philosophy": [
                "Signal Purification/Uncertainty",
                "Scale Issues (Spatial_Temporal)",
                "Multi-Source Integration",
                "Data Quality & Validation"
            ],
            "Modeling": [
                "Physics-Informed AI",
                "Causal Inference",
                "Hybrid Modeling (Process+ML)",
                "Ensemble Methods"
            ],
            "Dynamics": [
                "Non-linearity & Complexity",
                "Tipping Points",
                "Drought-Flood Transitions",
                "Rapid Onset Events"
            ],
            "Coupling": [
                "Vegetation-Water Interaction",
                "Energy-Water Nexus",
                "Human-Nature Systems",
                "Multi-Sphere Coupling"
            ]
        }
    }
}

# ================= 3. Profile & Cache Management =================

def load_user_profile():
    """Load user profile generated by profiler.py"""
    if os.path.exists(PROFILE_FILE):
        try:
            with open(PROFILE_FILE, 'r', encoding='utf-8') as f:
                profile = json.load(f)
            print(f"[OK] Loaded user profile from {PROFILE_FILE}")
            return profile
        except Exception as e:
            print(f"[WARN] Failed to load profile: {e}")

    # Default profile if file doesn't exist
    print("[INFO] Using default hydrology profile")
    return {
        "base_info": "Default Hydrology Researcher Profile",
        "dynamic_analysis": {
            "summary": "Focus on hydrological extremes and AI applications",
            "focus_areas": ["ET", "Flash Drought", "DFA", "Deep Learning"]
        }
    }

def load_cache():
    """Load collection ID cache from disk"""
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"[WARN] Failed to load cache: {e}")
    return {}

def save_cache(cache):
    """Save collection ID cache to disk"""
    try:
        with open(CACHE_FILE, 'w', encoding='utf-8') as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"[WARN] Failed to save cache: {e}")

def get_analysis_results_file(collection_path=None):
    """
    根据collection路径生成深度分析结果文件名
    
    Args:
        collection_path: Collection路径（如 "Precipitation"），None表示使用 TARGET_COLLECTION_PATH
    
    Returns:
        文件路径（如 "analysis_json/Precipitation_deep_analysis_results.json"）
    """
    if collection_path is None:
        collection_path = TARGET_COLLECTION_PATH
    
    if collection_path is None:
        return "analysis_json/global_deep_analysis_results.json"
    
    # 将路径转换为有效的文件名
    # 替换 '/' 为 '_'，空格替换为 '_'
    safe_name = collection_path.replace('/', '_').replace(' ', '_')
    # 移除其他可能的不安全字符
    safe_name = ''.join(c if c.isalnum() or c in ('_', '-') else '_' for c in safe_name)
    # 移除连续的下划线
    while '__' in safe_name:
        safe_name = safe_name.replace('__', '_')
    # 移除开头和结尾的下划线
    safe_name = safe_name.strip('_')
    
    return f"analysis_json/{safe_name}_deep_analysis_results.json"

def load_analysis_results():
    """Load previous analysis results from disk"""
    file_path = get_analysis_results_file()
    if os.path.exists(file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"[WARN] Failed to load analysis results: {e}")
    return {}

def save_analysis_results(results):
    """Save analysis results to disk"""
    file_path = get_analysis_results_file()
    try:
        # 确保目录存在
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"[WARN] Failed to save analysis results: {e}")

def refresh_cache_from_zotero(zot):
    """Fetch all collections from Zotero and build cache"""
    print("[REFRESH] Refreshing collection cache from Zotero...")
    try:
        # 获取所有 collections（包括用户创建的和系统默认的）
        # 使用分页方式确保获取所有 collections
        all_colls = []
        start = 0
        page_size = 100
        
        while True:
            try:
                page = zot.collections(limit=page_size, start=start)
                if not page:
                    break
                all_colls.extend(page)
                
                # 如果返回的数量少于 page_size，说明已经获取完所有数据
                if len(page) < page_size:
                    break
                
                start += page_size
            except Exception as page_error:
                print(f"   [WARN] Error fetching collections page (start={start}): {page_error}")
                break
        
        if not all_colls:
            print("   [WARN] No collections returned from Zotero API")
            return {}
        
        print(f"   [FETCH] Fetched {len(all_colls)} collections from Zotero API (using pagination)")
        
        cache = {}

        # Build a mapping from key to collection data for path reconstruction
        key_to_coll = {c['key']: c for c in all_colls}

        def build_full_path(coll):
            path = [coll['data']['name']]
            parent = coll['data'].get('parentCollection', None)
            while parent:
                parent_coll = key_to_coll.get(parent)
                if not parent_coll:
                    break
                path.insert(0, parent_coll['data']['name'])
                parent = parent_coll['data'].get('parentCollection', None)
            return '/'.join(path)

        # 收集所有顶级 collection 名称用于调试
        top_level_names = []
        all_collection_names = []  # 所有 collection 名称（用于调试）
        
        for c in all_colls:
            coll_name = c['data']['name']
            all_collection_names.append(coll_name)
            full_path = build_full_path(c)
            key = c['key']
            parent = c['data'].get('parentCollection', None)
            cache[full_path] = {
                'key': key,
                'parent': parent if parent else None
            }
            
            # 收集顶级 collection（没有父 collection 的）
            if not parent:
                top_level_names.append(coll_name)

        save_cache(cache)
        print(f"[OK] Cached {len(cache)} collections (by path)")
        
        # 调试：打印所有顶级 collection 名称（不限制数量）
        if top_level_names:
            print(f"   [SEARCH] Top-level collections ({len(top_level_names)}个): {', '.join(sorted(top_level_names))}")
        
        # 调试：检查是否包含 "0-New"
        if '0-New' in all_collection_names:
            print(f"   [OK] Found '0-New' in collections!")
            # 找到所有包含 "0-New" 的路径
            matching_paths = [p for p in cache.keys() if '0-New' in p]
            if matching_paths:
                print(f"   [SEARCH] Paths containing '0-New': {matching_paths[:10]}")
        else:
            print(f"   [WARN] '0-New' not found in collection names")
            print(f"   [INFO] All collection names (前50个): {', '.join(sorted(set(all_collection_names))[:50])}")
        
        return cache
    except Exception as e:
        print(f"[ERROR] Failed to fetch collections: {e}")
        import traceback
        print(f"[DEBUG] Error details: {traceback.format_exc()}")
        return {}

# ================= 4. Collection Management =================

def find_collection_by_path(zot, collection_path, cache):
    """
    Find collection key by path (e.g., "Parent/Child")
    Uses cache first, falls back to Zotero API if needed
    
    Handles two cases:
    1. Collection name itself contains '/' (e.g., "5 Runoff/Streamflow")
    2. Nested path (e.g., "Parent/Child")
    """
    if not collection_path:
        return None

    # 首先尝试直接匹配完整路径（有些 collection 名称本身就包含 '/'）
    if collection_path in cache:
        result_key = cache[collection_path]['key']
        print(f"   [OK] Found exact match: '{collection_path}' -> Key: {result_key[:8]}...")
        return result_key
    
    # 如果直接匹配失败，刷新缓存后再试一次
    if collection_path not in cache:
        print(f"   [WARN] Collection path '{collection_path}' not in cache, refreshing...")
        cache = refresh_cache_from_zotero(zot)
        if collection_path in cache:
            result_key = cache[collection_path]['key']
            print(f"   [OK] Found exact match after refresh: '{collection_path}' -> Key: {result_key[:8]}...")
            return result_key

    # 如果直接匹配仍然失败，尝试按路径分割的方式查找（用于嵌套路径）
    parts = [p.strip() for p in collection_path.split('/') if p.strip()]
    if not parts:
        return None

    # 调试：打印查找的路径部分
    print(f"   [SEARCH] Trying nested path search, path parts: {parts}")

    # Build full path step by step
    current_path = ''
    current_parent = None
    for i, part in enumerate(parts):
        current_path = '/'.join(parts[:i+1])
        print(f"   [SEARCH] Checking path: '{current_path}'")
        
        if current_path not in cache:
            print(f"   [WARN] Collection path '{current_path}' not in cache, refreshing...")
            cache = refresh_cache_from_zotero(zot)
            
            # 调试：打印所有缓存中的路径（前30个）
            cached_paths = list(cache.keys())[:30]
            print(f"   [SEARCH] Available cached paths (前30个): {cached_paths}")
            
            if current_path not in cache:
                # 尝试模糊匹配：查找包含该部分的路径
                matching_paths = [p for p in cache.keys() if part in p or p.endswith('/' + part) or p == part]
                if matching_paths:
                    print(f"   [INFO] Found similar paths: {matching_paths[:10]}")
                
                print(f"   [ERROR] Collection path '{current_path}' not found")
                print(f"   [INFO] Tip: 请检查 collection 名称是否正确，注意大小写和特殊字符")
                return None
        current_parent = cache[current_path]['key']
        print(f"   [OK] Found: '{current_path}' -> Key: {current_parent[:8]}...")
    return current_parent

def ensure_collection_path(zot, path, cache):
    """
    Create collection path if it doesn't exist
    Returns the final collection key
    """
    if not path or path == "Unclassified":
        return None

    parts = [p.strip() for p in path.split('/') if p.strip()]
    parent_key = None
    current_path = ''

    for i, part in enumerate(parts):
        current_path = '/'.join(parts[:i+1])
        # Check if collection exists in cache by full path
        if current_path in cache:
            coll_info = cache[current_path]
            found_key = coll_info['key']
        else:
            found_key = None

        # Create if doesn't exist
        if not found_key:
            if DRY_RUN:
                print(f"      [Dry Run] Would create: {current_path}")
                found_key = f"fake_{part}_{parent_key or 'root'}"
            else:
                print(f"      [CREATE] Creating collection: {current_path}")
                try:
                    payload = {'name': part}
                    if parent_key:
                        payload['parentCollection'] = parent_key

                    res = zot.create_collections([payload])

                    # Validate response exists
                    if not res:
                        print(f"      [ERROR] 创建集合失败: API返回空响应")
                        return None

                    # Validate response structure
                    if not isinstance(res, dict):
                        print(f"      [ERROR] 创建集合失败: API响应格式不正确 ({type(res)})")
                        return None

                    # Check for successful creation
                    if 'successful' not in res:
                        if 'failed' in res:
                            failed_info = res['failed']
                            print(f"      [ERROR] 创建集合失败: {failed_info}")
                        else:
                            print(f"      [ERROR] 创建集合失败: 响应中缺少'successful'字段")
                        return None

                    # Extract key from response
                    success_dict = res['successful']

                    # Validate success_dict is not empty
                    if not success_dict:
                        print(f"      [ERROR] 创建集合失败: 'successful'字段为空")
                        return None

                    # Validate success_dict is a dictionary
                    if not isinstance(success_dict, dict):
                        print(f"      [ERROR] 创建集合失败: 'successful'字段格式不正确 ({type(success_dict)})")
                        return None

                    # Extract the key from the first successful item
                    try:
                        first_value = list(success_dict.values())[0]
                        if not isinstance(first_value, dict):
                            print(f"      [ERROR] 创建集合失败: 成功项格式不正确")
                            return None

                        if 'key' not in first_value:
                            print(f"      [ERROR] 创建集合失败: 成功项缺少'key'字段")
                            return None

                        found_key = first_value['key']

                        # Validate key is a non-empty string
                        if not found_key or not isinstance(found_key, str):
                            print(f"      [ERROR] 创建集合失败: 返回的key无效 ({found_key})")
                            return None

                    except (IndexError, KeyError, TypeError) as extract_err:
                        print(f"      [ERROR] 创建集合失败: 无法提取key - {extract_err}")
                        return None

                    # Update cache
                    cache[current_path] = {
                        'key': found_key,
                        'parent': parent_key
                    }
                    save_cache(cache)
                    print(f"      [OK] Created: {current_path} (Key: {found_key})")

                except Exception as e:
                    error_msg = str(e)
                    if '400' in error_msg:
                        print(f"      [ERROR] 创建集合失败 (请求格式错误): {e}")
                    elif '403' in error_msg or 'Forbidden' in error_msg:
                        print(f"      [ERROR] 创建集合失败 (权限不足): {e}")
                    elif 'timeout' in error_msg.lower() or 'timed out' in error_msg.lower():
                        print(f"      [ERROR] 创建集合失败 (请求超时): {e}")
                    else:
                        print(f"      [ERROR] 创建集合失败: {e}")
                    return None

        parent_key = found_key

    return parent_key

# ================= 5. AI Classification =================

def parse_note_content(note_content):
    """解析完整的AI阅读报告笔记内容
    
    优先尝试从笔记中提取 JSON 块并解析，如果失败则回退到 regex 解析。
    
    Returns:
        dict: 包含解析出的各个部分的字典，包括：
            - 基础信息：title_en, title_zh, journal, date, doi, authors
            - 摘要：one_sentence_summary, keywords, research_question, highlights
            - 结构化数据：data_table (list of dicts), weaknesses (list), future_work (list)
            - 其他：abstract, key_literature, data_methods, full_text
    """
    import re
    
    # Remove HTML tags
    text = re.sub(r'<[^>]+>', '', note_content)
    
    # 初始化解析结果字典
    parsed = {
        'one_sentence_summary': '',
        'keywords': '',
        'title_zh': '',
        'title_en': '',
        'journal': '',
        'date': '',
        'doi': '',
        'authors': '',
        'abstract': '',
        'research_question': '',
        'highlights': [],
        'key_literature': [],
        'data_methods': '',
        'data_table': [],  # 新增：数据表列表
        'weaknesses': [],
        'future_work': [],
        'tags': [],  # 新增：标签列表
        'full_text': text[:5000],  # 保留前5000字符用于深度分析
        'json_parsed': False  # 标记是否成功解析了 JSON
    }
    
    # ========== 第一步：尝试提取并解析 JSON 块 ==========
    json_patterns = [
        r'```json\s*(\{.*?\})\s*```',  # 匹配 ```json {...} ```
        r'```\s*(\{.*?\})\s*```',      # 匹配 ``` {...} ```
        r'(\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\})',  # 匹配独立的 JSON 对象
    ]
    
    json_data = None
    for pattern in json_patterns:
        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)
        if match:
            json_str = match.group(1).strip()
            try:
                json_data = json.loads(json_str)
                if isinstance(json_data, dict):
                    parsed['json_parsed'] = True
                    # 提取所有字段
                    parsed['title_en'] = json_data.get('title_en', '')
                    parsed['title_zh'] = json_data.get('title_zh', '')
                    parsed['journal'] = json_data.get('journal', '')
                    parsed['date'] = json_data.get('date', '')
                    parsed['doi'] = json_data.get('doi', '')
                    parsed['one_sentence_summary'] = json_data.get('one_sentence_summary_zh', '') or json_data.get('one_sentence_summary', '')
                    parsed['tags'] = json_data.get('tags', [])
                    if isinstance(parsed['tags'], list):
                        # 将标签列表转换为关键词字符串（用于向后兼容）
                        parsed['keywords'] = ', '.join([str(t) for t in parsed['tags'] if t])
                    parsed['research_question'] = json_data.get('research_question', '')
                    parsed['highlights'] = json_data.get('highlights', [])
                    if not isinstance(parsed['highlights'], list):
                        parsed['highlights'] = []
                    # 提取 data_table（重要：用于 Track A 分类）
                    parsed['data_table'] = json_data.get('data_table', [])
                    if not isinstance(parsed['data_table'], list):
                        parsed['data_table'] = []
                    # 提取 weaknesses（重要：用于 Track B 分类）
                    parsed['weaknesses'] = json_data.get('weaknesses', [])
                    if not isinstance(parsed['weaknesses'], list):
                        parsed['weaknesses'] = []
                    # 提取 future_work（重要：用于 Track B 分类）
                    parsed['future_work'] = json_data.get('future_work', [])
                    if not isinstance(parsed['future_work'], list):
                        parsed['future_work'] = []
                    break  # 成功解析 JSON，跳出循环
            except json.JSONDecodeError:
                # JSON 解析失败，继续尝试下一个模式或回退到 regex
                continue
    
    # ========== 第二步：如果没有成功解析 JSON，使用 regex 回退 ==========
    if not parsed['json_parsed']:
        # 提取一句话总结
        summary_patterns = [
            r'一句话总结[^：:]*[：:]\s*([^\n]{5,100})',
            r'One-Sentence Summary[^：:]*[：:]\s*([^\n]{5,100})',
        ]
        for pattern in summary_patterns:
            match = re.search(pattern, text, re.IGNORECASE | re.MULTILINE)
            if match:
                parsed['one_sentence_summary'] = match.group(1).strip()
                break
        
        # 提取关键词/论文分类
        keyword_patterns = [
            r'论文分类[^：:]*[：:]\s*([^\n]+)',
            r'Keywords[^：:]*[：:]\s*([^\n]+)',
            r'关键词[^：:]*[：:]\s*([^\n]+)',
        ]
        for pattern in keyword_patterns:
            match = re.search(pattern, text, re.IGNORECASE | re.MULTILINE)
            if match:
                parsed['keywords'] = match.group(1).strip()
                break
        
        # 提取研究问题
        rq_patterns = [
            r'研究问题[^：:]*[：:]\s*([^\n]{10,200})',
            r'Research Question[^：:]*[：:]\s*([^\n]{10,200})',
        ]
        for pattern in rq_patterns:
            match = re.search(pattern, text, re.IGNORECASE | re.MULTILINE)
            if match:
                parsed['research_question'] = match.group(1).strip()
                break
        
        # 提取核心亮点（最多6个）
        highlight_pattern = r'[Hh][1-6][：:]\s*([^\n]{5,50})'
        highlights = re.findall(highlight_pattern, text)
        parsed['highlights'] = highlights[:6]
        
        # 提取主要不足
        weakness_pattern = r'[1-6][）)]\s*([^\n]{10,150})'
        weaknesses = re.findall(weakness_pattern, text)
        parsed['weaknesses'] = weaknesses[:6]
        
        # 提取未来工作方向
        future_pattern = r'方向 [A-C][：:]\s*科学问题[：:]\s*([^\n]{10,200})'
        future_works = re.findall(future_pattern, text)
        parsed['future_work'] = future_works[:3]
    
    return parsed

def extract_keywords_from_note(note_content):
    """Extract keywords/tags from AI-generated note (保持向后兼容)"""
    parsed = parse_note_content(note_content)
    if parsed['keywords']:
        return parsed['keywords']
    
    # Fallback: extract first 200 chars after "Summary" or "总结"
    import re
    text = re.sub(r'<[^>]+>', '', note_content)
    summary_match = re.search(r'(?:Summary|总结)[：:]\s*(.{1,200})', text, re.IGNORECASE)
    if summary_match:
        return summary_match.group(1).strip()
    
    return ""

def generate_report_filename(collection_path):
    """
    根据集合路径生成报告文件名
    
    Args:
        collection_path: 集合路径（如 "0 2025/12"），None 表示整个库
    
    Returns:
        文件路径（如 "analysis_json/global_research_opportunities_report.json" 或 "analysis_json/0_2025_12_research_opportunities_report.json"）
    """
    if collection_path is None:
        return "analysis_json/global_research_opportunities_report.json"
    
    # 将路径转换为有效的文件名
    # 替换 '/' 为 '_'，空格保留或替换为 '_'
    safe_name = collection_path.replace('/', '_').replace(' ', '_')
    # 移除其他可能的不安全字符
    safe_name = ''.join(c if c.isalnum() or c in ('_', '-') else '_' for c in safe_name)
    # 移除连续的下划线
    while '__' in safe_name:
        safe_name = safe_name.replace('__', '_')
    # 移除开头和结尾的下划线
    safe_name = safe_name.strip('_')
    
    return f"analysis_json/{safe_name}_research_opportunities_report.json"

def generate_global_analysis_report(analysis_results, user_profile, ai_model, ai_key):
    """
    生成全局分析报告：汇总所有论文的创新点和研究方向
    
    Args:
        analysis_results: 所有论文的分析结果字典
        user_profile: 用户画像
        ai_model: AI模型名称
        ai_key: AI API密钥
    """
    if not analysis_results or len(analysis_results) == 0:
        print("   [WARN] No analysis results to summarize")
        return
    
    print(f"   [ANALYSIS] Analyzing {len(analysis_results)} papers for global insights...")
    
    try:
        client = genai.Client(api_key=ai_key)
        
        # 收集所有论文的关键信息
        papers_summary = []
        all_innovation_insights = []
        all_keywords = []
        all_archive_paths = []
        all_idea_paths = []
        all_data_tables = []  # 新增：收集所有 data_table 条目
        
        for item_key, result in analysis_results.items():
            title = result.get('title', 'Unknown')
            innovation_insights = result.get('innovation_insights', [])
            keyword_assessment = result.get('keyword_assessment', {})
            archive_path = result.get('archive_path', '')
            idea_path = result.get('idea_path', '')
            
            papers_summary.append(f"- {title}")
            all_innovation_insights.extend(innovation_insights)
            all_keywords.append(keyword_assessment.get('suggested', keyword_assessment.get('current', '')))
            if archive_path:
                all_archive_paths.append(archive_path)
            if idea_path:
                all_idea_paths.append(idea_path)
            
            # 收集 data_table（从结构化元数据中提取）
            # 优先从 structured_metadata 中获取，如果没有则从顶层获取（向后兼容）
            structured_metadata = result.get('structured_metadata', {})
            data_table = structured_metadata.get('data_table', result.get('data_table', []))
            if data_table and isinstance(data_table, list):
                for dt in data_table:
                    if isinstance(dt, dict):
                        dt_with_paper = dt.copy()
                        dt_with_paper['paper_title'] = title  # 记录来源论文
                        all_data_tables.append(dt_with_paper)
        
        # 构建提示词
        profile_summary = user_profile.get('dynamic_analysis', {}).get('summary', 'General hydrology researcher')
        focus_areas = user_profile.get('dynamic_analysis', {}).get('focus_areas', [])
        
        prompt = f"""You are a Research Strategy Advisor for Prof. Chengming Li (Hydrology/Hydro-climatology).

USER PROFILE:
- Base: {user_profile.get('base_info', '')}
- Current Focus: {profile_summary}
- Key Areas: {', '.join(focus_areas)}

TASK: Analyze ALL {len(analysis_results)} papers that have been processed and provide:

1. **Research Landscape Overview**:
   - What are the main research themes across all papers?
   - What are the emerging research directions?
   - What are the common methodologies being used?

2. **Data Landscape** (NEW):
   - Analyze all data sources from the data_table entries across all papers
   - Identify common datasets (e.g., WorldPop, CEADs, MODIS, GPM, etc.)
   - Summarize data accessibility patterns (which datasets are commonly used vs. rare)
   - Note spatial and temporal resolution trends
   - Identify data gaps or underrepresented data sources
   - Suggest opportunities for data integration or new data combinations

3. **Cross-Paper Research Opportunities**:
   - Identify 5-8 research opportunities that bridge multiple papers
   - For each opportunity, explain:
     * Which papers are related
     * Why this is a promising direction
     * What specific research questions could be addressed
     * Potential methodologies or approaches

4. **Research Gaps and Future Directions**:
   - What gaps exist in the current research landscape?
   - What are the most promising future research directions?
   - What interdisciplinary opportunities exist?

5. **Keyword Trends**:
   - What are the most common keywords/themes?
   - Are there any emerging keywords that appear frequently?
   - What keyword combinations suggest new research areas?

PAPERS PROCESSED ({len(analysis_results)} papers):
{chr(10).join(papers_summary[:50])}  # 最多显示50篇

INNOVATION INSIGHTS COLLECTED ({len(all_innovation_insights)} insights):
{chr(10).join([f"- {insight}" for insight in all_innovation_insights[:30]])}  # 最多显示30个

ARCHIVE CLASSIFICATIONS:
{chr(10).join([f"- {path}" for path in list(set(all_archive_paths))[:20]])}  # 去重后显示前20个

IDEA LAB CLASSIFICATIONS:
{chr(10).join([f"- {path}" for path in list(set(all_idea_paths))[:20]])}  # 去重后显示前20个

DATA SOURCES COLLECTED ({len(all_data_tables)} entries):
{chr(10).join([f"- {dt.get('name', 'Unknown')} ({dt.get('source', 'Unknown')}) - Used in: {dt.get('paper_title', 'Unknown')}" for dt in all_data_tables[:30]])}  # 最多显示30个

OUTPUT: JSON format:
{{
  "research_landscape": {{
    "main_themes": ["theme1", "theme2", ...],
    "emerging_directions": ["direction1", "direction2", ...],
    "common_methodologies": ["method1", "method2", ...]
  }},
  "data_landscape": {{
    "common_datasets": [
      {{
        "name": "Dataset name (e.g., WorldPop)",
        "usage_count": 5,
        "papers_using": ["paper title 1", "paper title 2"],
        "typical_resolution": "spatial/temporal resolution",
        "accessibility": "public/restricted/unknown"
      }},
      ...
    ],
    "data_accessibility_summary": "Summary of which datasets are commonly accessible vs. restricted",
    "spatial_resolution_trends": ["trend1", "trend2", ...],
    "temporal_resolution_trends": ["trend1", "trend2", ...],
    "data_gaps": ["gap1", "gap2", ...],
    "integration_opportunities": ["opportunity1", "opportunity2", ...]
  }},
  "cross_paper_opportunities": [
    {{
      "title": "Opportunity title",
      "related_papers": ["paper title 1", "paper title 2"],
      "rationale": "Why this is promising",
      "research_questions": ["question1", "question2"],
      "methodologies": ["method1", "method2"]
    }},
    ...
  ],
  "research_gaps": [
    "gap description 1",
    "gap description 2",
    ...
  ],
  "future_directions": [
    "direction description 1",
    "direction description 2",
    ...
  ],
  "keyword_trends": {{
    "common_keywords": ["keyword1", "keyword2", ...],
    "emerging_keywords": ["keyword1", "keyword2", ...],
    "promising_combinations": ["combination1", "combination2", ...]
  }}
}}

JSON:"""
        
        print("   [AI] Calling AI for global analysis...")
        response = client.models.generate_content(
            model=ai_model,
            contents=prompt,
            config={'response_mime_type': 'application/json'}
        )
        
        if not response or not hasattr(response, 'text') or not response.text:
            print("   [WARN] AI返回空响应")
            return
        
        try:
            global_report = json.loads(response.text)
            
            # 根据 TARGET_COLLECTION_PATH 生成文件名
            report_file = generate_report_filename(TARGET_COLLECTION_PATH)
            # 确保目录存在
            os.makedirs(os.path.dirname(report_file), exist_ok=True)
            with open(report_file, 'w', encoding='utf-8') as f:
                json.dump(global_report, f, indent=2, ensure_ascii=False)
            
            print(f"   [OK] Global analysis report saved to: {report_file}")
            
            # 打印摘要
            print("\n   [DEBUG] Global Analysis Summary:")
            print("   " + "-" * 68)
            
            if 'research_landscape' in global_report:
                landscape = global_report['research_landscape']
                if 'main_themes' in landscape:
                    print(f"\n   [THEMES] Main Research Themes ({len(landscape['main_themes'])}):")
                    for theme in landscape['main_themes'][:5]:
                        print(f"      - {theme}")
            
            if 'cross_paper_opportunities' in global_report:
                opportunities = global_report['cross_paper_opportunities']
                print(f"\n   [INFO] Cross-Paper Research Opportunities ({len(opportunities)}):")
                for i, opp in enumerate(opportunities[:3], 1):
                    print(f"      {i}. {opp.get('title', 'Unknown')}")
                    if 'related_papers' in opp:
                        print(f"         Related papers: {', '.join(opp['related_papers'][:2])}...")
            
            if 'future_directions' in global_report:
                directions = global_report['future_directions']
                print(f"\n   [DIRECTIONS] Future Research Directions ({len(directions)}):")
                for direction in directions[:3]:
                    print(f"      - {direction[:80]}...")
            
            if 'data_landscape' in global_report:
                data_landscape = global_report['data_landscape']
                print(f"\n   [DATA] Data Landscape Summary:")
                if 'common_datasets' in data_landscape:
                    common_datasets = data_landscape['common_datasets']
                    print(f"      Common Datasets ({len(common_datasets)}):")
                    for ds in common_datasets[:5]:
                        name = ds.get('name', 'Unknown')
                        count = ds.get('usage_count', 0)
                        print(f"         - {name} (used in {count} papers)")
                if 'data_gaps' in data_landscape:
                    gaps = data_landscape['data_gaps']
                    if gaps:
                        print(f"      Data Gaps ({len(gaps)}):")
                        for gap in gaps[:3]:
                            print(f"         - {gap[:70]}...")
            
            print(f"\n   [SAVED] Full report saved to: {report_file}")
            
        except json.JSONDecodeError as e:
            print(f"   [WARN] Failed to parse global analysis JSON: {e}")
            print(f"   [PREVIEW] Response preview: {response.text[:200]}")
            
    except Exception as e:
        print(f"   [WARN] Failed to generate global analysis: {e}")
        import traceback
        print(f"   [DEBUG] Error details: {traceback.format_exc()}")

def format_taxonomy_for_prompt():
    """Convert taxonomy to compact text format for AI prompt"""
    lines = []

    for track_name, track_data in PREFERRED_TAXONOMY.items():
        emoji = track_data.get('emoji', '')
        desc = track_data.get('description', '')

        track_label = track_name.replace('_', ' ').replace('Track A', '[ARCHIVE] Archive').replace('Track B', '[IDEA] Idea Lab')
        lines.append(f"\n{track_label} ({desc}):")

        for category, subcategories in track_data['structure'].items():
            lines.append(f"\n  {category}:")
            for subcat in subcategories:
                lines.append(f"    - {subcat}")

    return "\n".join(lines)

def ai_dual_classify_batch(batch_items, user_profile, ai_model, ai_key):
    """
    深度分析并分类论文，包括：
    1. 双轨分类（Archive + Idea Lab）
    2. 关键词评估
    3. 论文关联分析
    4. 创新点思考

    Returns: dict with format {
        "0": {
            "archive": "path1", 
            "idea": "path2",
            "keyword_assessment": {"current": "...", "suggested": "...", "reason": "..."},
            "related_papers": ["title1", "title2"],
            "innovation_insights": ["insight1", "insight2"]
        }, 
        ...
    }
    """
    client = genai.Client(api_key=ai_key)

    # Format papers with structured fields for deep analysis
    papers_list = []
    for i, item in enumerate(batch_items):
        note_content = item.get('note_content', '')
        parsed_note = parse_note_content(note_content) if note_content else {}
        
        # 构建结构化数据表字符串（用于 Track A 分类）
        data_table_str = ""
        data_table = parsed_note.get('data_table', [])
        if data_table and isinstance(data_table, list):
            data_table_str = "\nData Sources:\n"
            for idx, dt in enumerate(data_table[:5], 1):  # 最多显示5个数据源
                if isinstance(dt, dict):
                    name = dt.get('name', 'Unknown')
                    source = dt.get('source', 'Unknown')
                    spatial_res = dt.get('spatial_res', 'Unknown')
                    temporal_res = dt.get('temporal_res', 'Unknown')
                    data_table_str += f"  {idx}. {name} ({source}) - Spatial: {spatial_res}, Temporal: {temporal_res}\n"
        else:
            data_table_str = "Data Sources: Not specified in structured format\n"
        
        # 构建弱点列表字符串（用于 Track B 分类）
        weaknesses_str = ""
        weaknesses = parsed_note.get('weaknesses', [])
        if weaknesses and isinstance(weaknesses, list):
            weaknesses_str = "\nWeaknesses:\n" + "\n".join([f"  - {w}" for w in weaknesses[:6] if w])
        else:
            weaknesses_str = "\nWeaknesses: Not specified in structured format\n"
        
        # 构建未来工作列表字符串（用于 Track B 分类）
        future_work_str = ""
        future_work = parsed_note.get('future_work', [])
        if future_work and isinstance(future_work, list):
            future_work_str = "\nFuture Work Directions:\n" + "\n".join([f"  - {fw}" for fw in future_work[:3] if fw])
        else:
            future_work_str = "\nFuture Work: Not specified in structured format\n"
        
        paper_info = f"""Paper {i}:
Title: {item['title']}
Title (EN): {parsed_note.get('title_en', '')}
Title (ZH): {parsed_note.get('title_zh', '')}
Journal: {parsed_note.get('journal', '')}
DOI: {parsed_note.get('doi', '')}
Keywords (current): {item.get('keywords', '')}
One-sentence Summary: {parsed_note.get('one_sentence_summary', '')}
Research Question: {parsed_note.get('research_question', '')}
Highlights: {', '.join(parsed_note.get('highlights', [])[:3])}
{data_table_str}
{weaknesses_str}
{future_work_str}
Note Content (excerpt): {parsed_note.get('full_text', '')[:800]}
"""
        papers_list.append(paper_info)

    papers_text = "\n".join(papers_list)

    # Extract profile summary
    profile_summary = user_profile.get('dynamic_analysis', {}).get('summary', 'General hydrology researcher')
    focus_areas = user_profile.get('dynamic_analysis', {}).get('focus_areas', [])

    # Build compact prompt
    taxonomy_text = format_taxonomy_for_prompt()

    prompt = f"""You are a Research Assistant for Prof. Chengming Li (Hydrology/Hydro-climatology).

USER PROFILE:
- Base: {user_profile.get('base_info', '')}
- Current Focus: {profile_summary}
- Key Areas: {', '.join(focus_areas)}

TASK: For each paper, perform DEEP ANALYSIS and provide:
1. **Dual-Track Classification**:
   - Archive Track ([ARCHIVE]): Standard subject/method classification for retrieval
     * IMPORTANT: Use the "Data Sources" section to help classify by methodology/data type
     * Examples: If data_table shows "Remote Sensing" sources → Methodology/Remote Sensing/Retrieval
     * If data_table shows "MRIO Model" → Methodology/MRIO (if exists) or Methodology/Statistical Methods
     * Group papers by common data sources (e.g., WorldPop, CEADs, MODIS) when appropriate
   - Idea Lab Track ([IDEA]): Scientific question/mechanism classification for exploration
     * IMPORTANT: Use "Weaknesses" and "Research Question" to identify mechanism/scale/data philosophy issues
     * Examples: If weaknesses mention "scale issues" → Data Philosophy/Scale Issues
     * If research_question focuses on "mechanisms" → Mechanism/...
     * If weaknesses mention "uncertainty" → Data Philosophy/Signal Purification/Uncertainty

2. **Keyword Assessment**:
   - Evaluate if current keywords are accurate and comprehensive
   - Suggest improvements if needed
   - Explain your reasoning

3. **Paper Relationships**:
   - Identify potential connections with other papers in the batch
   - Note: You can only see papers in this batch, so focus on relationships within the batch
   - Consider: shared data sources, similar weaknesses, complementary future work directions

4. **Innovation Insights**:
   - Based on the paper's content, research question, weaknesses, and future work suggestions
   - Think about: What new research directions or opportunities does this paper suggest?
   - What gaps or limitations could be addressed in future work?

TAXONOMY (Use these paths or suggest logical sub-paths):
{taxonomy_text}

PAPERS TO ANALYZE:
{papers_text}

OUTPUT: JSON with format:
{{
  "0": {{
    "archive": "[ARCHIVE] Archive/Category/Subcategory",
    "idea": "[IDEA] Idea Lab/Category/Subcategory",
    "keyword_assessment": {{
      "current": "current keywords from note",
      "suggested": "improved keywords if needed, or 'current keywords are good'",
      "reason": "brief explanation"
    }},
    "related_papers": ["Paper X title", "Paper Y title"],
    "innovation_insights": [
      "insight 1: what new research could be done",
      "insight 2: what gaps could be filled"
    ]
  }},
  "1": {{...}},
  ...
}}

Return "Unclassified" for classification if unsure. Use exact emoji prefixes and path separators (/).

JSON:"""

    try:
        response = client.models.generate_content(
            model=ai_model,
            contents=prompt,
            config={'response_mime_type': 'application/json'}
        )

        # Validate response exists and has text attribute
        if not response:
            print(f"   [ERROR] AI返回空响应")
            return {}

        if not hasattr(response, 'text') or not response.text:
            print(f"   [ERROR] AI响应缺少文本内容")
            return {}

        # Validate JSON structure
        try:
            result = json.loads(response.text)
        except json.JSONDecodeError as json_err:
            print(f"   [ERROR] AI响应不是有效的JSON: {json_err}")
            print(f"   [PREVIEW] 响应内容前100字符: {response.text[:100]}")
            return {}

        # Validate result is a dictionary
        if not isinstance(result, dict):
            print(f"   [ERROR] AI返回的JSON不是字典格式: {type(result)}")
            return {}

        # Validate each entry has the expected structure
        valid_results = {}
        for key, value in result.items():
            if not isinstance(value, dict):
                print(f"   [WARN] 跳过无效的分类项 {key}: 值不是字典")
                continue

            # Check for required fields
            if 'archive' not in value and 'idea' not in value:
                print(f"   [WARN] 跳过无效的分类项 {key}: 缺少'archive'或'idea'字段")
                continue

            # Validate archive and idea are strings
            archive = value.get('archive', '')
            idea = value.get('idea', '')

            if not isinstance(archive, str):
                print(f"   [WARN] 分类项 {key}: 'archive'不是字符串，使用默认值")
                archive = "Unclassified"

            if not isinstance(idea, str):
                print(f"   [WARN] 分类项 {key}: 'idea'不是字符串，使用默认值")
                idea = "Unclassified"

            # 提取深度分析结果
            keyword_assessment = value.get('keyword_assessment', {})
            related_papers = value.get('related_papers', [])
            innovation_insights = value.get('innovation_insights', [])

            valid_results[key] = {
                'archive': archive, 
                'idea': idea,
                'keyword_assessment': keyword_assessment if isinstance(keyword_assessment, dict) else {},
                'related_papers': related_papers if isinstance(related_papers, list) else [],
                'innovation_insights': innovation_insights if isinstance(innovation_insights, list) else []
            }

        if not valid_results:
            print(f"   [WARN] AI分类结果没有有效项目")
            return {}

        print(f"   [AI] AI成功分类 {len(valid_results)} 篇论文")
        return valid_results

    except Exception as e:
        error_msg = str(e)
        if 'timeout' in error_msg.lower() or 'timed out' in error_msg.lower():
            print(f"   [ERROR] AI请求超时: {e}")
        elif 'rate limit' in error_msg.lower() or 'quota' in error_msg.lower():
            print(f"   [ERROR] AI API速率限制或配额不足: {e}")
        elif 'model' in error_msg.lower() or 'not found' in error_msg.lower():
            print(f"   [ERROR] AI模型错误: {e}")
        elif 'api key' in error_msg.lower() or 'authentication' in error_msg.lower():
            print(f"   [ERROR] AI API密钥错误: {e}")
        else:
            print(f"   [ERROR] AI分类错误: {e}")
        return {}

# ================= 6. Item Fetching =================

def get_all_subcollection_keys(zot, parent_key, cache):
    """递归获取所有子collection的keys（包括子子collection等）
    
    Args:
        zot: Zotero client instance
        parent_key: 父collection的key
        cache: collection缓存字典，格式为 {path: {'key': key, 'parent': parent_key}}
    
    Returns:
        List of collection keys（包括父collection本身和所有子collection）
    """
    all_keys = [parent_key]  # 包括父collection本身
    
    # 方法1: 从cache中查找所有parent字段等于parent_key的collection（直接子collection）
    direct_children = []
    for path, info in cache.items():
        if info.get('parent') == parent_key:
            direct_children.append(info['key'])
    
    # 递归处理每个直接子collection
    for child_key in direct_children:
        if child_key not in all_keys:
            all_keys.append(child_key)
            # 递归获取子collection的所有子collection
            sub_keys = get_all_subcollection_keys(zot, child_key, cache)
            all_keys.extend([k for k in sub_keys if k not in all_keys])
    
    # 方法2: 如果cache中没有找到，尝试从Zotero API获取所有collections并查找
    if not direct_children:
        try:
            # 获取所有collections
            all_colls = []
            start = 0
            page_size = 100
            while True:
                page = zot.collections(limit=page_size, start=start)
                if not page:
                    break
                all_colls.extend(page)
                if len(page) < page_size:
                    break
                start += page_size
            
            # 查找所有parentCollection等于parent_key的collection
            for coll in all_colls:
                coll_parent = coll['data'].get('parentCollection')
                if coll_parent == parent_key:
                    child_key = coll['key']
                    if child_key not in all_keys:
                        all_keys.append(child_key)
                        # 递归获取子collection的所有子collection
                        sub_keys = get_all_subcollection_keys(zot, child_key, cache)
                        all_keys.extend([k for k in sub_keys if k not in all_keys])
        except Exception as e:
            print(f"   [WARN] Error fetching subcollections: {e}")
    
    return list(set(all_keys))  # 去重

def fetch_all_items(zot, target_coll_key=None, tag=None, cache=None, include_subcollections=True):
    """Fetch all items from Zotero with pagination support, optionally including subcollections
    
    Args:
        zot: Zotero client instance
        target_coll_key: Target collection key (None for entire library)
        tag: Filter by tag name (e.g., 'gemini_read')
        cache: Collection cache (required if include_subcollections=True)
        include_subcollections: If True, recursively fetch items from all subcollections
    
    Returns:
        List of items
    """
    # 如果指定了collection且需要包含子collection，先获取所有相关collection keys
    collection_keys = [target_coll_key] if target_coll_key else None
    
    if target_coll_key and include_subcollections and cache:
        print(f"   [INFO] 递归获取所有子collection中的文献...")
        collection_keys = get_all_subcollection_keys(zot, target_coll_key, cache)
        print(f"   [INFO] 找到 {len(collection_keys)} 个collection（包括主collection和所有子collection）")
    
    all_items = []
    
    # 如果没有指定collection，从整个库获取
    if not collection_keys:
        start = 0
        page_size = 100
        while True:
            try:
                page = zot.items(tag=tag, limit=page_size, start=start)
                if not page:
                    break
                all_items.extend(page)
                if len(page) < page_size:
                    break
                start += page_size
            except Exception as e:
                print(f"   [WARN] Error fetching items (start={start}): {e}")
                break
    else:
        # 从每个collection中获取items
        total_collections = len(collection_keys)
        for idx, coll_key in enumerate(collection_keys, 1):
            # 每10个collection或开始时输出进度
            if idx % 10 == 0 or idx == 1 or idx == total_collections:
                print(f"   [INFO] 正在获取items ({idx}/{total_collections} collections)...")
            
            start = 0
            page_size = 100
            while True:
                try:
                    page = zot.collection_items(coll_key, tag=tag, limit=page_size, start=start)
                    if not page:
                        break
                    all_items.extend(page)
                    if len(page) < page_size:
                        break
                    start += page_size
                except Exception as e:
                    print(f"   [WARN] Error fetching items from collection {coll_key[:8]}... (start={start}): {e}")
                    break
    
    # 去重（同一个item可能在多个collection中）
    seen_keys = set()
    unique_items = []
    for item in all_items:
        item_key = item.get('key', '')
        if item_key and item_key not in seen_keys:
            seen_keys.add(item_key)
            unique_items.append(item)
    
    return unique_items

# ================= 7. Item Processing =================

def validate_collection_keys(zot, collection_keys):
    """验证collection keys是否存在，返回有效的keys列表"""
    if not collection_keys:
        return []
    
    valid_keys = []
    for key in collection_keys:
        # 跳过fake keys
        if key.startswith("fake_"):
            continue
        
        # 尝试获取collection来验证它是否存在
        try:
            coll = zot.collection(key)
            if coll and isinstance(coll, dict) and coll.get('data'):
                valid_keys.append(key)
        except Exception:
            # Collection不存在或无法访问，跳过
            pass
    
    return valid_keys

def add_item_to_collections(zot, item, collection_keys):
    """Add item to multiple collections and mark with tag"""
    if not collection_keys:
        return

    # Filter out fake keys
    new_keys = [k for k in collection_keys if not k.startswith("fake_")]

    if not new_keys:
        return

    if DRY_RUN:
        return

    try:
        # item 应为 key 字符串
        item_key = item if isinstance(item, str) else item.get('key')
        if not item_key:
            print(f"      [ERROR] Invalid item key")
            return

        # 获取当前 item 的完整数据
        item_full = zot.item(item_key)
        if isinstance(item_full, list) and len(item_full) > 0:
            item_full = item_full[0]
        
        if not isinstance(item_full, dict):
            print(f"      [WARN] Could not get item: unexpected format")
            return
        
        # 获取 data 字段
        item_data = item_full.get('data', {})
        if not isinstance(item_data, dict):
            print(f"      [WARN] Item data is not a dict: {type(item_data)}")
            return
        
        # 获取当前的 collections
        current_collections = item_data.get('collections', [])
        if not isinstance(current_collections, list):
            current_collections = []
        
        # 验证所有collection keys（包括现有的和新的）
        all_collection_keys = list(set(current_collections + new_keys))
        valid_collection_keys = validate_collection_keys(zot, all_collection_keys)
        
        # 如果有些keys无效，记录清理信息
        invalid_keys = set(all_collection_keys) - set(valid_collection_keys)
        if invalid_keys:
            print(f"      [INFO] Removed {len(invalid_keys)} invalid collection key(s)")
        
        # 合并新的有效 collections（去重）
        updated_collections = list(set(valid_collection_keys))
        
        # 检查并添加 tag
        current_tags = item_data.get('tags', [])
        if not isinstance(current_tags, list):
            current_tags = []
        
        # 检查 tag 是否已存在
        tag_exists = False
        for tag in current_tags:
            if isinstance(tag, dict):
                if tag.get('tag') == AUTO_TAG_NAME:
                    tag_exists = True
                    break
            elif isinstance(tag, str):
                if tag == AUTO_TAG_NAME:
                    tag_exists = True
                    break
        
        # 如果 tag 不存在，添加它
        needs_update = False
        if not tag_exists:
            current_tags.append({'tag': AUTO_TAG_NAME})
            item_data['tags'] = current_tags
            needs_update = True
        
        # 如果 collections 有变化，也更新
        if set(updated_collections) != set(current_collections):
            item_data['collections'] = updated_collections
            needs_update = True
        
        # 如果有任何变化，更新 item
        if needs_update:
            item_full['data'] = item_data
            try:
                update_result = zot.update_item(item_full)
                if update_result:
                    collection_msg = f"Added to {len([k for k in new_keys if k in valid_collection_keys])} collection(s)" if set(updated_collections) != set(current_collections) else ""
                    tag_msg = f"Tagged: {AUTO_TAG_NAME}" if not tag_exists else ""
                    msgs = [m for m in [collection_msg, tag_msg] if m]
                    if msgs:
                        print(f"      [OK] {'; '.join(msgs)}")
                else:
                    print(f"      [WARN] Failed to update item")
            except Exception as update_error:
                import traceback
                error_msg = str(update_error)
                # 检查是否是409错误（collection not found）
                if '409' in error_msg or 'not found' in error_msg.lower():
                    print(f"      [WARN] Collection not found, cleaning invalid keys and retrying...")
                    # 再次验证并清理
                    item_full_retry = zot.item(item_key)
                    if isinstance(item_full_retry, list) and len(item_full_retry) > 0:
                        item_full_retry = item_full_retry[0]
                    if isinstance(item_full_retry, dict):
                        item_data_retry = item_full_retry.get('data', {})
                        if isinstance(item_data_retry, dict):
                            current_collections_retry = item_data_retry.get('collections', [])
                            if isinstance(current_collections_retry, list):
                                valid_collections_retry = validate_collection_keys(zot, current_collections_retry)
                                item_data_retry['collections'] = valid_collections_retry
                                item_full_retry['data'] = item_data_retry
                                try:
                                    zot.update_item(item_full_retry)
                                    print(f"      [OK] Cleaned invalid collection keys")
                                except:
                                    print(f"      [ERROR] Failed to clean invalid keys")
                else:
                    print(f"      [ERROR] Failed to update item: {update_error}")
                    print(f"      [DEBUG] Error details: {traceback.format_exc()}")
        else:
            print(f"      [INFO] Item already in all target collections and has tag")

    except Exception as e:
        print(f"      [ERROR] Failed to add to collections: {e}")
        import traceback
        print(f"      [DEBUG] Error details: {traceback.format_exc()}")

# ================= 8. Main Processing =================

def main():
    print("=" * 70)
    print("[AI] Zotero AI Paper Organizer - Dual-Track Classification System")
    print("=" * 70)
    print(f"Mode: {'[DRY RUN] DRY RUN (Test Mode)' if DRY_RUN else '[LIVE] LIVE MODE'}")
    print(f"Batch Size: {BATCH_SIZE}")
    print(f"Target Collection: {TARGET_COLLECTION_PATH or 'Entire Library'}")
    print("=" * 70)

    # Initialize
    zot = zotero.Zotero(config.LIBRARY_ID, config.LIBRARY_TYPE, config.API_KEY)

    # Load user profile
    user_profile = load_user_profile()

    # Load or refresh cache
    cache = load_cache()
    if not cache:
        cache = refresh_cache_from_zotero(zot)
    else:
        print(f"[OK] Loaded {len(cache)} collections from cache")

    # Find target collection if specified
    target_coll_key = None
    if TARGET_COLLECTION_PATH:
        print(f"\n[SEARCH] Looking for collection: {TARGET_COLLECTION_PATH}")
        # 如果缓存为空或很小，先刷新一次
        if not cache or len(cache) < 10:
            print("   [REFRESH] Cache is empty or small, refreshing...")
            cache = refresh_cache_from_zotero(zot)
        
        target_coll_key = find_collection_by_path(zot, TARGET_COLLECTION_PATH, cache)
        
        # 如果没找到，刷新缓存后再试一次
        if not target_coll_key:
            print("   [REFRESH] Retrying after full cache refresh...")
            cache = refresh_cache_from_zotero(zot)
            target_coll_key = find_collection_by_path(zot, TARGET_COLLECTION_PATH, cache)

        if not target_coll_key:
            print("[ERROR] Target collection not found. Exiting.")
            print(f"[INFO] 提示：请确认 collection 路径 '{TARGET_COLLECTION_PATH}' 是否正确")
            print(f"[INFO] 注意：路径区分大小写，请检查是否有空格或特殊字符")
            return

        print(f"[OK] Found collection (Key: {target_coll_key})")

    # Fetch items to process
    print("\n[SEARCH] Fetching items...")

    if target_coll_key:
        items = fetch_all_items(zot, target_coll_key, tag='gemini_read', cache=cache, include_subcollections=True)
        print(f"   Scope: Collection '{TARGET_COLLECTION_PATH}' (包括所有子目录)")
    else:
        items = fetch_all_items(zot, tag='gemini_read', include_subcollections=False)
        print(f"   Scope: Entire library")

    print(f"   Found: {len(items)} items with 'gemini_read' tag")

    # Filter items that haven't been organized yet
    todo_items = []
    skipped_organized = 0
    skipped_no_note = 0
    found_notes = 0

    for item in items:
        # Skip note items (notes themselves, not papers)
        item_type = item.get('data', {}).get('itemType', '')
        if item_type == 'note':
            # 这是笔记本身，不是论文，跳过
            skipped_no_note += 1
            continue
        
        # Skip if already has auto_organized tag
        tags = [t.get('tag', '') for t in item.get('data', {}).get('tags', [])]
        if AUTO_TAG_NAME in tags:
            skipped_organized += 1
            continue

        # 获取笔记（完整内容）
        # 策略：使用与test_find_note.py相同的逻辑，确保能找到笔记
        note_content = ""
        keywords = ""
        note_count = 0
        
        # 获取item key（使用与test_find_note.py相同的简单方式）
        item_key = item.get('key', '')
        
        if not item_key:
            if skipped_no_note < 3:
                title = item.get('data', {}).get('title', 'Unknown')[:50]
                print(f"      [WARN] Cannot get item key for '{title}...'")
            skipped_no_note += 1
            continue
        
        # 尝试获取子项（笔记）- 使用与test_find_note.py相同的逻辑
        children = []
        try:
            children = zot.children(item_key)
            if not isinstance(children, list):
                children = []
        except Exception as children_error:
            # 某些item类型可能不支持children方法
            error_str = str(children_error)
            if "can only be called on" in error_str or "PDF, EPUB" in error_str:
                children = []
            else:
                # 其他错误，打印调试信息
                if skipped_no_note < 3:
                    title = item.get('data', {}).get('title', 'Unknown')[:50]
                    print(f"      [WARN] Error getting children for '{title}...': {children_error}")
                    print(f"         Item key: {item_key}")
                children = []
        
        # 遍历所有子项，查找笔记（使用与test_find_note.py相同的逻辑）
        for child in children:
            # 使用与test_find_note.py相同的简单方式获取类型
            child_type = child.get('data', {}).get('itemType', 'unknown')
            
            if child_type == 'note':
                note_count += 1
                # 使用与test_find_note.py相同的简单方式获取笔记内容
                current_note = child.get('data', {}).get('note', '')
                if current_note and current_note.strip():
                    # 找到第一个有效笔记就使用（不要求格式）
                    if not note_content:
                        note_content = current_note
                        # 尝试解析关键词（可选）
                        try:
                            parsed = parse_note_content(note_content)
                            keywords = parsed.get('keywords', '')
                        except:
                            keywords = ""
                        found_notes += 1
                        break  # 使用第一个有效笔记即可
        
        # 调试：如果没有找到任何笔记
        if not note_content:
            skipped_no_note += 1
            if skipped_no_note <= 3:  # 只打印前3个
                title = item.get('data', {}).get('title', 'Unknown')[:50]
                item_type = item.get('data', {}).get('itemType', 'unknown')
                print(f"      [WARN] Item '{title}...' (type: {item_type}) has NO notes")
                print(f"         Item key: {item_key}")
                print(f"         Children count: {len(children)}")
                if children:
                    # 使用与test_find_note.py相同的简单方式获取类型
                    child_types = [c.get('data', {}).get('itemType', 'unknown') for c in children]
                    print(f"         Child types: {child_types}")

        # 只要有笔记内容，就添加到待处理列表
        if note_content:
            item_title = item.get('data', {}).get('title', 'Untitled') if isinstance(item, dict) else 'Untitled'
            todo_items.append({
                'key': item_key,
                'data': item.get('data', {}) if isinstance(item, dict) else {},
                'title': item_title,
                'keywords': keywords,
                'note_content': note_content  # 保存完整笔记内容用于深度分析
            })

    # 打印详细的统计信息
    print(f"\n[STATS] Processing Statistics:")
    print(f"   Total items with 'gemini_read' tag: {len(items)}")
    print(f"   Skipped (already organized): {skipped_organized}")
    print(f"   Skipped (no notes): {skipped_no_note}")
    print(f"   Found notes: {found_notes}")
    print(f"[OK] Items to organize: {len(todo_items)}")
    
    # 如果所有items都被跳过了，提供更多信息
    if len(todo_items) == 0 and len(items) > 0:
        print(f"\n[INFO] Debug Info:")
        print(f"   - {skipped_organized} items already have '{AUTO_TAG_NAME}' tag")
        print(f"   - {skipped_no_note} items don't have any notes")
        if skipped_no_note > 0:
            print(f"   [INFO] Tip: 请确保论文有笔记（任何格式的笔记都可以）")

    if not todo_items:
        print("\n[INFO] No items to process!")
        return

    # Load previous analysis results
    analysis_results = load_analysis_results()
    
    # Process in batches
    total_batches = math.ceil(len(todo_items) / BATCH_SIZE)
    organized_count = 0

    for batch_idx in range(total_batches):
        batch = todo_items[batch_idx * BATCH_SIZE : (batch_idx + 1) * BATCH_SIZE]

        print(f"\n[BATCH] Batch {batch_idx + 1}/{total_batches} ({len(batch)} items)")
        print("-" * 70)

        # AI dual classification
        print("   [AI] Calling AI for dual-track classification...")
        classifications = ai_dual_classify_batch(batch, user_profile, config.AI_MODEL, config.AI_API_KEY)

        # Process each classification
        for idx_str, paths in classifications.items():
            try:
                idx = int(idx_str)
                if idx >= len(batch):
                    continue

                item_info = batch[idx]
                print(f"\n   [{idx}] {item_info['title'][:60]}...")

                # Extract paths
                archive_path = paths.get('archive', '')
                idea_path = paths.get('idea', '')

                print(f"      [ARCHIVE] Archive: {archive_path}")
                print(f"      [IDEA] Idea Lab: {idea_path}")

                # 显示关键词评估
                keyword_assessment = paths.get('keyword_assessment', {})
                if keyword_assessment:
                    current_kw = keyword_assessment.get('current', '')
                    suggested_kw = keyword_assessment.get('suggested', '')
                    reason = keyword_assessment.get('reason', '')
                    if suggested_kw and suggested_kw != current_kw:
                        print(f"      [KEYWORDS] 关键词评估:")
                        print(f"         当前: {current_kw}")
                        print(f"         建议: {suggested_kw}")
                        if reason:
                            print(f"         原因: {reason}")

                # 显示论文关联
                related_papers = paths.get('related_papers', [])
                if related_papers:
                    print(f"      [RELATED] 论文关联: {len(related_papers)} 篇")
                    for rp in related_papers[:3]:  # 最多显示3个
                        print(f"         - {rp[:50]}...")

                # 显示创新点洞察
                innovation_insights = paths.get('innovation_insights', [])
                if innovation_insights:
                    print(f"      [INSIGHT] 创新点洞察: {len(innovation_insights)} 条")
                    for insight in innovation_insights[:2]:  # 最多显示2个
                        print(f"         - {insight[:80]}...")

                # Collect keys
                collection_keys = []

                # Ensure archive path exists
                if archive_path and archive_path != "Unclassified":
                    archive_key = ensure_collection_path(zot, archive_path, cache)
                    if archive_key:
                        collection_keys.append(archive_key)

                # Ensure idea lab path exists
                if idea_path and idea_path != "Unclassified":
                    idea_key = ensure_collection_path(zot, idea_path, cache)
                    if idea_key:
                        collection_keys.append(idea_key)

                # Add to collections
                if collection_keys:
                    if DRY_RUN:
                        print(f"      [Dry Run] Would add to {len(collection_keys)} collection(s)")
                    else:
                        add_item_to_collections(zot, item_info['key'], collection_keys)

                    organized_count += 1
                    
                    # 保存分析结果到文件（包含完整的结构化元数据）
                    item_key = item_info['key']
                    note_content = item_info.get('note_content', '')
                    parsed_note = parse_note_content(note_content) if note_content else {}
                    
                    analysis_results[item_key] = {
                        'title': item_info['title'],
                        'archive_path': archive_path,
                        'idea_path': idea_path,
                        'keyword_assessment': paths.get('keyword_assessment', {}),
                        'related_papers': paths.get('related_papers', []),
                        'innovation_insights': paths.get('innovation_insights', []),
                        'processed_time': time.strftime('%Y-%m-%d %H:%M:%S'),
                        # 新增：存储完整的结构化元数据
                        'structured_metadata': {
                            'title_en': parsed_note.get('title_en', ''),
                            'title_zh': parsed_note.get('title_zh', ''),
                            'journal': parsed_note.get('journal', ''),
                            'date': parsed_note.get('date', ''),
                            'doi': parsed_note.get('doi', ''),
                            'authors': parsed_note.get('authors', ''),
                            'one_sentence_summary': parsed_note.get('one_sentence_summary', ''),
                            'research_question': parsed_note.get('research_question', ''),
                            'highlights': parsed_note.get('highlights', []),
                            'data_table': parsed_note.get('data_table', []),  # 重要：用于 Data Landscape 分析
                            'weaknesses': parsed_note.get('weaknesses', []),  # 重要：用于 Track B 分类
                            'future_work': parsed_note.get('future_work', []),  # 重要：用于 Track B 分类
                            'tags': parsed_note.get('tags', []),
                            'json_parsed': parsed_note.get('json_parsed', False)  # 标记是否从 JSON 解析
                        }
                    }
                    save_analysis_results(analysis_results)

            except Exception as e:
                print(f"   [ERROR] Error processing item {idx_str}: {e}")

        # Rate limiting
        if batch_idx < total_batches - 1:
            print("\n   [WAIT] Waiting 3s before next batch...")
            time.sleep(3)

    # Summary
    print("\n" + "=" * 70)
    print("📊 Summary")
    print("=" * 70)
    print(f"Total items processed: {len(todo_items)}")
    print(f"Successfully organized: {organized_count}")
    print(f"Mode: {'DRY RUN (no changes made)' if DRY_RUN else 'LIVE MODE (changes saved)'}")
    analysis_results_file = get_analysis_results_file()
    print(f"Analysis results saved to: {analysis_results_file}")
    print("=" * 70)
    
    # 全局分析：生成汇总报告（如果有新处理的论文）
    if organized_count > 0:
        print("\n" + "=" * 70)
        print("🔬 全局分析：生成研究机会汇总报告")
        print("=" * 70)
        # 重新加载所有分析结果（包括之前处理的）
        all_analysis_results = load_analysis_results()
        if len(all_analysis_results) >= 3:  # 至少3篇论文才进行全局分析
            generate_global_analysis_report(all_analysis_results, user_profile, config.AI_MODEL, config.AI_API_KEY)
        else:
            print(f"   [INFO] 当前只有 {len(all_analysis_results)} 篇论文，建议至少3篇后再进行全局分析")
    
    print("\n🎉 Done!")

    if DRY_RUN:
        print("\n[INFO] Tip: Set DRY_RUN = False in organizer.py to actually organize items")
    
    analysis_results_file = get_analysis_results_file()
    print(f"\n[INFO] 深度分析结果已保存到 {analysis_results_file}")
    print(f"   您可以查看该文件来了解：")
    print(f"   - 关键词评估建议")
    print(f"   - 论文之间的关联")
    print(f"   - 创新点洞察和研究方向")
    report_filename = generate_report_filename(TARGET_COLLECTION_PATH)
    print(f"\n[INFO] 全局研究机会报告：{report_filename}")
    print(f"   - 跨论文研究机会")
    print(f"   - 研究空白和未来方向")
    print(f"   - 关键词趋势分析")

if __name__ == "__main__":
    main()
